### PR TITLE
fix: widget overflow

### PR DESCRIPTION
**Pull request by bhattabhi013**
## Description

Fixed the widget overflow by changing the margin of `HomepageCard`. 
Fixes issue #34.

screenshot:
image

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by bhattabhi013** [comment]
Hi @Jatinpandya26,
Can you please review it?

**Comment by bhattabhi013** [comment]
Can you please look into this @Jatinpandya26 ?

**Comment by ghost** [comment]
> Can you please look into this @Jatinpandya26 ?

Hi Abhishek,
I did have a look over this and there seems to be some error in your build as it's not taking an atKey into account. We had it put on hold to check it.

**Comment by bhattabhi013** [comment]
How can I resolve this?

**Pull request closed without merging**
